/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class AltaProducto extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public AltaProducto() {
        initComponents();
    }
    
    /*private void setImageLabel(JLabel labelname, String root)
    {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon
        (
                image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.Scale)
        );
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        txtGanacia = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        txtExistencia = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        txtMedidas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        titulo.setForeground(new java.awt.Color(5, 93, 38));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Alta Producto");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 140, 40));

        jLabel2.setText("Clave");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 120, -1));

        jLabel3.setText("Tipo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, -1));

        jLabel4.setText("Existencia");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, -1));

        jLabel5.setText("Categoria");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 120, -1));

        jLabel7.setText("Precio de compra");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, -1));

        jLabel6.setText("Ganancia");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 120, -1));
        add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 280, 30));
        add(txtGanacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 280, 30));
        add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 280, 30));
        add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 280, 30));
        add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 80, 30));
        add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 280, 30));

        btnCancelar.setBackground(new java.awt.Color(204, 38, 38));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 160, -1));

        btnAceptar.setBackground(new java.awt.Color(5, 93, 38));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 160, -1));
        add(txtMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 280, 30));

        jLabel8.setText("Medidas LxA");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtGanacia;
    private javax.swing.JTextField txtMedidas;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
