/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import negocio.EmpleadosControl;

/**
 *
 * @author hg710
 */
public class CambiarContra extends javax.swing.JPanel {
private final EmpleadosControl control;
int clave;
    /**
     * Creates new form NewJPanel
     */
    public CambiarContra(int clave) {
        this.clave = clave;
        control = new EmpleadosControl();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNuevaContrasena = new javax.swing.JTextField();
        txtConfirmarContrasena = new javax.swing.JTextField();
        txtContrasenaAntigua = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Contraseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 280, -1));

        jLabel5.setText("Nueva contraseña");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 280, -1));

        jLabel6.setText("Confirmar contraseña");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 280, -1));
        add(txtNuevaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 280, 30));
        add(txtConfirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 280, 30));
        add(txtContrasenaAntigua, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 280, 30));

        btnCancelar.setBackground(new java.awt.Color(204, 38, 38));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 160, -1));

        btnAceptar.setBackground(new java.awt.Color(5, 93, 38));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(txtContrasenaAntigua.getText().isEmpty() || txtNuevaContrasena.getText().isEmpty() || txtConfirmarContrasena.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Hay campos vacios...", "Madereria La Cienega", JOptionPane.WARNING_MESSAGE);
        else
        {
            if(!txtNuevaContrasena.getText().equals(txtConfirmarContrasena.getText()))
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden...", "Madereria La Cienega", JOptionPane.WARNING_MESSAGE);
            else if(txtNuevaContrasena.getText().length() < 8)
                JOptionPane.showMessageDialog(this, "La contraseña debe ser de mas de 8 caracteres...", "Madereria La Cienega", JOptionPane.WARNING_MESSAGE);
            else
            {
                String res = control.ActualizarContra(clave, txtContrasenaAntigua.getText(), txtConfirmarContrasena.getText());
                JOptionPane.showMessageDialog(this, res, "Madereria La Cienega", JOptionPane.INFORMATION_MESSAGE);
                txtConfirmarContrasena.setText("");
                txtNuevaContrasena.setText("");
                txtContrasenaAntigua.setText("");
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtConfirmarContrasena;
    private javax.swing.JTextField txtContrasenaAntigua;
    private javax.swing.JTextField txtNuevaContrasena;
    // End of variables declaration//GEN-END:variables
}
